language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_8b5367522756_key -iv $encrypted_8b5367522756_iv -in pixelvore_rsa.enc -out pixelvore_rsa -d
install:
  - ./bootstrap.py
script:
  - ./ve/bin/flake8 pixelvore/main
  - ./manage.py test
after_success:
  - chmod 600 pixelvore_rsa
  - make travis_deploy
