# fly.toml file generated for pixelvore on 2021-10-30T10:15:03+01:00

app = "pixelvore"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ALLOWED_HOSTS="pixelvore.thraxil.org,pixelvore.fly.dev"
  DB_USER="pixelvore_mk1zpx29496jrve0"
  DB_PORT="5432"
  DB_HOST="thraxil-postgres.internal"
  AWS_S3_CUSTOM_DOMAIN="d18gpprm4r04fx.cloudfront.net"
  AWS_STORAGE_BUCKET_NAME="thraxil-pixelvore-static-prod"

[deploy]
  release_command = "/run.sh migrate && /run.sh collectstatic && /run.sh compress"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/smoketest/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
        Host="pixelvore.fly.dev"
